// <auto-generated />
using System;
using AprajitaRetails.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AprajitaRetails.Migrations.Accounts
{
    [DbContext(typeof(AprajitaRetailsContext))]
    partial class AprajitaRetailsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AprajitaRetails.Areas.Accounts.Models.LedgerMaster", b =>
                {
                    b.Property<int>("LedgerMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LedgerType")
                        .HasColumnType("int");

                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.HasKey("LedgerMasterId");

                    b.HasIndex("PartyId")
                        .IsUnique();

                    b.ToTable("Masters");
                });

            modelBuilder.Entity("AprajitaRetails.Areas.Accounts.Models.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GSTNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LedgerType")
                        .HasColumnType("int");

                    b.Property<decimal>("OpenningBalance")
                        .HasColumnType("money");

                    b.Property<DateTime>("OpenningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PANNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("AprajitaRetails.Areas.Accounts.Models.LedgerMaster", b =>
                {
                    b.HasOne("AprajitaRetails.Areas.Accounts.Models.Party", "Party")
                        .WithOne("LedgerMaster")
                        .HasForeignKey("AprajitaRetails.Areas.Accounts.Models.LedgerMaster", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
